name: flutter_fit_utils_provider
description: "A flutter package to easily create providers of modelable data. This package is part of the flutter_fit_utils environement."
version: 2.1.4
homepage: https://pub.dev/packages/flutter_fit_utils_provider
repository: https://github.com/s0punk/flutter_fit_utils_provider
issue_tracker: https://github.com/s0punk/flutter_fit_utils_provider/issues

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

topics:
  - provider

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_fit_utils: ^2.4.3
  provider: ^6.1.2
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0